version: "3.8"

services:
    web:
        build: ./
        env_file:
            - ./.env
        volumes:
            - ./server/src:/src
            - ./server/static:/static
        command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn automation_apps.wsgi -b 0.0.0.0:80"
        expose:
            - 80
        depends_on:
            - postgres
        restart: always

    postgres:
        image: postgres:14.4
        env_file:
            - ./.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always

    nginx:
        image: nginx:1.23
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./nginx/ssl:/ssl
            - ./server/static:/static
        depends_on:
            - web
        restart: always

volumes:
    postgres-data:
