version: "3.8"

services:
    client:
        build: ./client
        command: sh -c "npm run serve"
        ports:
            - 8080:8080

    api:
        build: ./api
        env_file:
            - ./.env
        environment:
            - DEBUG=1
        volumes:
            - ./api/src:/src
            - ./api/static:/static
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:14.4
        env_file:
            - ./.env
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
